### Ejercicio 2 - sección 3.3.5

In [2]:
#Importamos bibliotecas
import sympy as sp
import numpy as np
from fractions import Fraction
import torch as tc

Dados los tensores $R^{i}_{j} = \begin{pmatrix} 1/2 & 1 & 3/2 \\ 2 & 5/2 & 3 \\ 7/2 & 4 & 9/2\end{pmatrix}$, $~T^{i} = \begin{pmatrix} 1/3 \\  2/3  \\ 1 \end{pmatrix}$, $~~g^{ij} = g_{ij} =  \begin{pmatrix} 1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$,

Encuentre: 

_**a)**_ La parte simétrica $S^{i}_j$ y antisimétrica $A^{i}_j$ de $R^{i}_j$.

In [3]:
#Creamos los tensores
R= np.array([[1/2, 1, 3/2],[2, 5/2, 3], [7/2, 4, 9/2]]) 
T = np.array([1/3,2/3,1])
g = np.array([[1, 0, 0],[0, -1, 0], [0, 0, 1]])


In [4]:
#Descomponemos el tensor R en sus componentes simétricas y antisimétricas
R_s = (R + R.T)/2
R_a = (R - R.T)/2

#Imprimimos los resultados en forma de matriz
print("La parte simétrica de R es = \n",R_s)
print("La parte antisimétrica de R es = \n", (R_a))


La parte simétrica de R es = 
 [[0.5 1.5 2.5]
 [1.5 2.5 3.5]
 [2.5 3.5 4.5]]
La parte antisimétrica de R es = 
 [[ 0.  -0.5 -1. ]
 [ 0.5  0.  -0.5]
 [ 1.   0.5  0. ]]


_**b)**_  ¿Qué se concluye de estos cálculos?
$R_{kj} = g_{ik}R^{i}_j,~ ~R^{ki} = g^{jk}R^{i}_j, ~~T_j = g_{ij}T^{i}$

Se concluye que el tensor $g_i{ij}$ sirve para subir o bajar índices de los demás tensores. Sin embargo, al existir ese "-1" en $g$, los tensores no se mantienen invariantes, solo se conservan los elementos de la diagonal y el elemento del centro cambia de signo.

In [5]:
#Multiplicamos los componentes del tensor R por el tensor g
R_k = np.einsum('ik, ij -> kj', g, R)
print("El tensor R_k es = \n", R_k)


#Multiplicamos los componentes del tensor R por el tensor g
R_k = np.einsum('jk, ij -> ki', g, R)
print("El tensor R_k es = \n", R_k)

#Multiplicación de g por T, queda una matriz de 3x1
gT = np.einsum('ij, i -> j', g, T)
print("El tensor gT es = \n", gT)


El tensor R_k es = 
 [[ 0.5  1.   1.5]
 [-2.  -2.5 -3. ]
 [ 3.5  4.   4.5]]
El tensor R_k es = 
 [[ 0.5  2.   3.5]
 [-1.  -2.5 -4. ]
 [ 1.5  3.   4.5]]
El tensor gT es = 
 [ 0.33333333 -0.66666667  1.        ]


_**c)**_ $R^{i}_j T_i = $

In [6]:
#producto entre los tensores R y T
a = np.einsum('ij, i -> j', R, T)
print("El tensor a es = \n", a)

El tensor a es = 
 [5. 6. 7.]


$R^{i}_j T^{j} =$

In [7]:
b = np.einsum('ij, j -> i', R, T)
print("El tensor b es = \n", b)

El tensor b es = 
 [2.33333333 5.33333333 8.33333333]


$R^{i}_j T_i T^{j} = $

In [8]:
c = np.einsum('ij, i->j', R, T)
c = np.einsum('j, j', c, T)
print("El tensor c es = \n", c)

El tensor c es = 
 12.666666666666666


_**d)**_ $R^{i}_j S^{j}_i=$

In [9]:
a = np.einsum('ij, ji', R, R_s)
print("El tensor a es = \n", a)

El tensor a es = 
 68.25


$R^{i}_j A^j_i=$

In [10]:
b = np.einsum('ij, ji', R, R_a)
print("El tensor b es = \n", b)

El tensor b es = 
 -3.0


$A^{j}_i T^{i}=$

In [11]:
c = np.einsum('ij, i -> j', R_a, T)
print("El tensor c es = \n", c)


El tensor c es = 
 [ 1.33333333  0.33333333 -0.66666667]


$A^{j}_iT^{i}T_j=$

In [12]:
d = np.einsum('i, j', T, T)
d = np.einsum('ij, ij', R_a, d)
print("El tensor d es = \n", d)


El tensor d es = 
 0.0


_**e)**_ $R^{i}_j - 2 \delta^{i}_jR^{l}_l=$

In [13]:
#Definimos el tensor de kronecker
k = np.eye(3)
a = np.einsum('ij', R) - 2* np.einsum('ij, ll', k, R)
print("El tensor a es = \n", a)


El tensor a es = 
 [[-14.5   1.    1.5]
 [  2.  -12.5   3. ]
 [  3.5   4.  -10.5]]


$(R^{i}_j - 2 \delta^{i}_jR^{l}_l)T_i=$

In [17]:
b = np.einsum('ij, i->j', a, T)
print("El tensor b es = \n", b)

El tensor b es = 
 [ 0. -4. -8.]


$(R^{i}_j - 2 \delta^{i}_jR^{l}_l) T_iT^{j}=$

In [21]:
c = np.einsum('ij, i->j', a, T)
de = np.einsum('j, j', c, T)
print("El tensor d es = \n", de)

El tensor d es = 
 -10.666666666666666
