**Nombre:** Santiago Andrés Montes Camacho
**Código:** 2210718

In [4]:
import numpy as np

In [5]:
R= np.array([[1/2, 1, 3/2],[2, 5/2, 3], [7/2, 4, 9/2]]) 
T = np.array([1/3,2/3,1]) #Sacrificio que debe hacerse---Tomar esto como vector fila ¿¿?? 
g = np.array([[1, 0, 0],[0, -1, 0], [0, 0, 1]])
d = np.eye(3)

In [6]:
#Debido a la situación de T, los resultados que den tensores de rango 1 (vectores) deben ajustarse como fila o columna manualmente 

## A)

In [7]:
def simetric(a):
    result = (1/2) * (a + a.T)
    return result

In [8]:
def antisim(b):
    result = (1/2) * (b - b.T)
    return result
    
    

In [9]:
S = simetric(R)
print("El simétrico de Ri_j es: ")
print(S)

El simétrico de Ri_j es: 
[[0.5 1.5 2.5]
 [1.5 2.5 3.5]
 [2.5 3.5 4.5]]


In [10]:
A = antisim(R)
print("El antisimétrico de Ri_j es: ")
print(A)

El antisimétrico de Ri_j es: 
[[ 0.  -0.5 -1. ]
 [ 0.5  0.  -0.5]
 [ 1.   0.5  0. ]]


## B) 


In [11]:
np.einsum('ik,ij->kj',g, R)

array([[ 0.5,  1. ,  1.5],
       [-2. , -2.5, -3. ],
       [ 3.5,  4. ,  4.5]])

In [12]:
np.einsum('jk,ij->ki',g, R)

array([[ 0.5,  2. ,  3.5],
       [-1. , -2.5, -4. ],
       [ 1.5,  3. ,  4.5]])

In [13]:
np.einsum('ij,i->j',g,T)

array([ 0.33333333, -0.66666667,  1.        ])

## C)

In [14]:
np.einsum('ij,i',R,T)

array([5., 6., 7.])

In [15]:
np.einsum('ij,j',R,T) #revisar

array([2.33333333, 5.33333333, 8.33333333])

In [16]:
np.einsum('ij,i,j',R,T,T) #revisar

12.666666666666666

## D)

In [17]:
np.einsum('ij,ji',R,S)

68.25

In [18]:
np.einsum('ij,ji',R,A)

-3.0

In [19]:
np.einsum('ji,i',A,T)

array([-1.33333333, -0.33333333,  0.66666667])

In [26]:
np.einsum('ji,i,j',A,T,T) #revisar

0.0

## E

In [21]:
np.einsum('ij',R) - 2*(np.einsum('ij,ll',d,R))

array([[-14.5,   1. ,   1.5],
       [  2. , -12.5,   3. ],
       [  3.5,   4. , -10.5]])

In [22]:
(np.einsum('ij,i',R,T) - 2*(np.einsum('ij,ll,i',d,R,T))) #revisar

array([ 0., -4., -8.])

In [148]:
(np.einsum('ij,i,j',R,T,T) - 2*(np.einsum('ij,ll,i,j',d,R,T,T))) #revisar

-10.666666666666666