**Nombre:** Santiago Andrés Montes Camacho.
**Código:** 2210718

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([3,2,1])
d = np.array([6,5,4])

### A) Encuentre:

In [6]:
V = a + b + c + d
V

array([14, 14, 14])

In [7]:
W = a + b - c - d
W

array([-4,  0,  4])

In [8]:
X = a - b + c - d
X

array([-6, -6, -6])

In [9]:
Z = - a + b - c + d
Z

array([6, 6, 6])

### B) Ángulo entre a,b,c,d y los vectores base


In [10]:
#Norma de cada vector a,b,c,d
n_a=np.sqrt(np.dot(a,a))
n_b=np.sqrt(np.dot(b,b))
n_c=np.sqrt(np.dot(c,c))
n_d=np.sqrt(np.dot(d,d))

**Vector a**:

In [11]:
#Se calculan los ángulos alpha, beta y gamma para el vector a
alpha_a = np.round(np.degrees(np.arccos(a[0]/n_a)),2)
beta_a = np.round(np.degrees(np.arccos(a[1]/n_a)),2) 
gamma_a = np.round(np.degrees(np.arccos(a[2]/n_a)),2)

print('Ángulo 1: ' + str(alpha_a))
print('Ángulo 2: ' + str(beta_a))
print('Ángulo 3: ' + str(gamma_a))

Ángulo 1: 74.5
Ángulo 2: 57.69
Ángulo 3: 36.7


**Vector b**:

In [13]:
#Se calculan los ángulos alpha, beta y gamma para el vector b

alpha_b = np.round(np.degrees(np.arccos(b[0]/n_b)),2)
beta_b = np.round(np.degrees(np.arccos(b[1]/n_b)),2)
gamma_b = np.round(np.degrees(np.arccos(b[2]/n_b)),2)

print('Ángulo 1: ' + str(alpha_b))
print('Ángulo 2: ' + str(beta_b))
print('Ángulo 3: ' + str(gamma_b))

Ángulo 1: 62.88
Ángulo 2: 55.26
Ángulo 3: 46.86


**Vector c:**

In [126]:
#Se calculan los ángulos alpha, beta y gamma para el vector c

alpha_c = np.round(np.degrees(np.arccos(c[0]/n_c)),2)
beta_c = np.round(np.degrees(np.arccos(c[1]/n_c)),2)
gamma_c = np.round(np.degrees(np.arccos(c[2]/n_c)),2)

print('Ángulo 1: ' + str(alpha_c))
print('Ángulo 2: ' + str(beta_c))
print('Ángulo 3: ' + str(gamma_c))

Ángulo 1: 36.7
Ángulo 2: 57.69
Ángulo 3: 74.5


**Vector d:**

In [127]:
#Se calculan los ángulos alpha, beta y gamma para el vector d

alpha_d = np.round(np.degrees(np.arccos(d[0]/n_d)),2)
beta_d = np.round(np.degrees(np.arccos(d[1]/n_d)),2)
gamma_d = np.round(np.degrees(np.arccos(d[2]/n_d)),2)

print('Ángulo 1: ' + str(alpha_d))
print('Ángulo 2: ' + str(beta_d))
print('Ángulo 3: ' + str(gamma_d))

Ángulo 1: 46.86
Ángulo 2: 55.26
Ángulo 3: 62.88


### C) Magnitud de los vectores a,b,c,d

In [52]:
#Esto ya lo utilizamos para calcular el ejercicio anterior, luego podemo simplemente llamar las mismas variables
print('La norma de a es: '+ str(np.round(n_a,2)))
print('La norma de b es: '+ str(np.round(n_b,2)))
print('La norma de c es: '+ str(np.round(n_c,2)))
print('La norma de d es: '+ str(np.round(n_d,2)))

La norma de a es: 3.74
La norma de b es: 8.77
La norma de c es: 3.74
La norma de d es: 8.77


###  D) Ángulo entre a y b y entre c y d

In [20]:
theta_1 = np.round(np.degrees(np.arccos(np.dot(a,b)/((n_a)*(n_b)))),2)
theta_2 = np.round(np.degrees(np.arccos(np.dot(a,c)/((n_a)*(n_c)))),2)
theta_3 = np.round(np.degrees(np.arccos(np.dot(a,d)/((n_a)*(n_d)))),2)
theta_4 = np.round(np.degrees(np.arccos(np.dot(b,c)/((n_b)*(n_c)))),2)
theta_5 = np.round(np.degrees(np.arccos(np.dot(b,d)/((n_b)*(n_d)))),2)
theta_6 = np.round(np.degrees(np.arccos(np.dot(c,d)/((n_c)*(n_d)))),2)


print("El ángulo entre a y b es: " + str(theta_1))
print("El ángulo entre a y c es: " + str(theta_2))
print("El ángulo entre a y d es: " + str(theta_3))
print("El ángulo entre b y c es: " + str(theta_4))
print("El ángulo entre b y d es: " + str(theta_5))
print("El ángulo entre c y d es: " + str(theta_6))

El ángulo entre a y b es: 12.93
El ángulo entre a y c es: 44.42
El ángulo entre a y d es: 31.48
El ángulo entre b y c es: 31.48
El ángulo entre b y d es: 18.55
El ángulo entre c y d es: 12.93


### E) Proyección de a sobre b

In [19]:
P = np.round(np.dot(a,b)*b/(n_b**2),2)
print("La proyección de a sobre b es: " + str(P))

La proyección de a sobre b es: [1.66 2.08 2.49]


### F) ¿Son los vectores a,b,c,d coplanares?

Dado que son 4 vectores y la dimensión del espacio es n = 3, luego los 4 vectores son linealmente dependientes. En este sentido se presenta una coplanaridad entre estos.

### G) Encuentre (a+b).(c+d)

In [77]:
R = np.dot((a+b),(c+d))
print('El resultado es: ' + str(R))

El resultado es: 139


### H) Hallar los productos axb, bxc, cxd y los ángulos que forman con d

In [17]:
R1 = np.cross(a,b)
R2 = np.cross(b,c)
R3 = np.cross(c,d)

n_R1 = np.round(np.sqrt(np.dot(R1,R1)),2)
n_R2 = np.round(np.sqrt(np.dot(R2,R2)),2)
n_R3 = np.round(np.sqrt(np.dot(R3,R3)),2)

beta_1 = np.round(np.degrees(np.arccos(np.dot(R1,d)/((n_R1)*(n_d)))),2)
beta_2 = np.round(np.degrees(np.arccos(np.dot(R2,d)/((n_R2)*(n_d)))),2)
beta_3 = np.round(np.degrees(np.arccos(np.dot(R3,d)/((n_R3)*(n_d)))),2)

print('El producto axb es: ' + str(R1) + ' y forma un ángulo de: ' + str(beta_1) + '° con el vector d')
print('El producto axb es: ' + str(R2) + ' y forma un ángulo de: ' + str(beta_2) + '° con el vector d')
print('El producto axb es: ' + str(R3) + ' y forma un ángulo de: ' + str(beta_3) + '° con el vector d')

El producto axb es: [-3  6 -3] y forma un ángulo de: 90.0° con el vector d
El producto axb es: [-7 14 -7] y forma un ángulo de: 90.0° con el vector d
El producto axb es: [ 3 -6  3] y forma un ángulo de: 90.0° con el vector d


### I) Hallar c.(axb)

In [115]:
T = np.dot(c, np.cross(a,b))
print('El resultado es: ' + str(T))

El resultado es: 0
